volumes:
  switchblend:
    name: switchblend

services:
  switchblend:
    image: .
    container_name: switchblend
    environment:
      - TZ=${TZ}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - 5000:5000
    volumes:
      - switchblend:/app/downloads:rw
    restart: unless-stopped
