volumes:
  switchblend_arch:
    name: switchblend_arch # Optional
  switchblend_conf:
    name: switchblend_conf # Optional

services:
  switchblend:
    image: .
    container_name: switchblend
    environment:
      - TZ=${TZ}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - UPDATE_INTERVAL=${UPDATE_INTERVAL}
    ports:
      - 5000:5000
    volumes:
      - switchblend_arch:/app/downloads:rw # Optional
      - switchblend_conf:/app/config:rw # Optional
    restart: unless-stopped
